pulp/pulp-service

- Dockerfile
- images/assets/3460e4bdc4bac870941a66dc65c1b7710250f652.diff
https://github.com/pulp/pulpcore/pull/4882
> Add patch to fix content_unit fixture

- deploy/clowdapp.yaml
> Fix the admin password having a newline in it

- deploy/clowdapp.yaml
- Fixes the usage of protocol on the collector URL.
- Disable the Traces exporter.
> Disable the Traces exporter and fixes collector URL.

- pr_check.sh
> Fix resources being removed

- Dockerfile
- deploy/clowdapp.yaml
- images/assets/ff94c61ced3d7f3722272ada7cb452e3ecfacd7a.diff
This is a patch to fix https://github.com/pulp/pulp_rpm/issues/3381
> Patches pulp_rpm until the fix is released

- deploy/clowdapp.yaml
- pr_check.sh
- pulp-smash.json
- unit_test.sh
> Run pulp_rpm functional tests as unit_test.sh

- Dockerfile
- unit_test.sh
Reviewers: Confirm that the test test_rbac_crud gets run
[noissue]
> Update for pulp_rpm 3.25 and pulpcore 3.44.1

- Dockerfile
- images/assets/pulp_gem-209-fix.diff
PR: https://github.com/pulp/pulp_gem/pull/215
> Patch for https://github.com/pulp/pulp_gem/issues/209

- deploy/clowdapp.yaml
> Re-implement migrations as a container

- Dockerfile
> Bump versions of pulpcore & pulp_gem

- deploy/clowdapp.yaml
but let role-assignment properly fail
> always treat user and role creation as having completed

- Dockerfile
- deploy/clowdapp.yaml
- images/assets/b55047ed0b7a3a378d703d1f38ab88939110f8a0.patch
> Add a livenessProbe based on the new liveness API

- Dockerfile
> Adds OSTree support

- deploy/clowdapp.yaml
> Exclude /livez api calls from alerts and SLOs

- Dockerfile
- deploy/clowdapp.yaml
> Adds integration with GlitchTip

- deploy/clowdapp.yaml
Creates a insights-cicd user and domain that belongs to that user. Creates a rubygems.org pull through cache.
PULP-59
> Adds a ClowderJob to create insights-cicd resources

- deploy/clowdapp.yaml
This param is passed to pulpcore-api
> Adds PULP_API_GUNICORN_WORKERS parameter

- deploy/clowdapp.yaml
> clowdapp.yaml: Provide `PULP_CONTENT_ORIGIN` to `reset-admin-password`

- deploy/clowdapp.yaml
This reverts commit 1aca780962d3ac98d83c267600bcfc08c7a9931a.
> Re-enable opentelemetry for api workers

- deploy/dashboards/grafana-dashboard-pulp.configmap.yaml
Also improve usage of space by changing the label.
Fixes: PULP-87
> Fix disk usage not being shown on grafana dashboard

- Dockerfile
This package allows us to inspect the clowder config using Python. This includes information about the DB, Redis, S3.
> Adds app-common-python to the image

- Dockerfile
- images/repos.d/centos8-base.repo
- images/repos.d/centos8-powertools.repo
- images/repos.d/centos8-stream.repo
- images/repos.d/centos9-appstream.repo
- images/repos.d/centos9-crb.repo
Also slim down the image a little bit, and do some work to make python configurable.
fixes: PULP-86
> Upgrade image to UBI9

- pr_check.sh
This will deploy the apps using whatever is in stage which is where PRs are deployed after being merged.
> pr_check: use insights-stage as ref-env

- Dockerfile
- unit_test.sh
PULP-92
PULP-97
Uses this change: https://github.com/mikedep333/pulp-openapi-scratch-builds/commit/dbca7ae211df8b4e318fca45d10c3164c20d21e7
> Slim down image and run ostree tests

- unit_test.sh
> Run plugin functional tests in parallel

- deploy/clowdapp.yaml
> Add the new parameter PULP_LIST_OF_ADMINS

- deploy/clowdapp.yaml
in favor of the clowder-created pulp-otel-collector
This must be merged 1st:
https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/109199
RHCLOUD-33333
> Cleanup the manually created pulp-otel-collector-svc

- deploy/clowdapp.yaml
> Reduce gunicorn workers to 1 in ephemeral.

- Dockerfile
> Add Python plugin to deployment

- pr_check.sh
Until Konflux can do tests successfully
PULP-110
> Revert cleaning up the Jenkins pr_check.sh

- deploy/clowdapp.yaml
This will add /O=rhds/OU=serviceaccounts/UID=ounsal to the admins.
> Re-run the admins user job.

- Dockerfile
- deploy/clowdapp.yaml
- images/assets/add_signing_service.sh
- images/assets/pulp-resource-manager
- images/assets/pulp-worker
- images/assets/set_init_password.sh
- images/assets/wait_on_database_migrations.sh
- unit_test.sh
the RPM modified file check
PULP-108
> Update to use virtualenv so as to safely pass

- .tekton/pulp-deploy-and-test.yaml
[PULP-125](https://issues.redhat.com/browse/PULP-125)
IGNORE THE CHANGES TO pulp-pull-request.yaml and pulp-push.yaml. I will undo them before merge; they are byproducts of the fact that I am testing in my repo, [which you should check out.](https://github.com/mikedep333/pulp-service/pull/2)
After merging we [update this file](https://github.com/redhat-appstudio/tenants-config/blob/main/auto-generated/cluster/stone-prd-rh01/tenants/pulp-services-tenant/appstudio.redhat.com_v1beta1_integrationtestscenario_pulp-bonfire-tekton.yaml) (or just delete it and then recreate it in [the webui.](https://console.redhat.com/preview/application-pipeline/workspaces/pulp-services/applications/pulp/integrationtests))
Jenkins will not be cleaned up until we create [the ReleasePlan and …
> Konflux Functional Tests

- .tekton/pulp-deploy-and-test.yaml
> Fix not running deploy-and-test on push

- Dockerfile
(Doing this in an early separate PR makes my development easier)
HMS-4347
> Add watchtower package for Cloudwatch/Kibana

- deploy/clowdapp.yaml
This reverts commit e470325c43f1b2f687cb7c396a9f81c763c0a836.
> Revert "Re-enable the removal of sha1 checksums (#220)"

- deploy/clowdapp.yaml
This should introduce new admin users (lmjachky, decko, bmbouter) for production.
> Re-run the admins user job

- deploy/clowdapp.yaml
> Add a Transform Processor to fix the metric's help messages.

- deploy/clowdapp.yaml
> Revert "Disable metrics reporting for API"

- deploy/clowdapp.yaml
- **Reduce the OTEL_METRIC_EXPORT_TIMEOUT to 7s**
- **Reduce the OTEL_METRIC_EXPORT_INTERVAL**
> change otel export time

- images/assets/patches/0001-Add-the-the-worker-name-to-all-metric-data-points.patch
- pulp_service/requirements.txt
That should add a new pulp_space_usage_bytes metric.
> Bump up the pulpcore requirement

- deploy/dashboards/grafana-dashboard-pulp.configmap.yaml
> Add a graph for displaying RPM/XML requests ratio

- deploy/dashboards/grafana-dashboard-pulp.configmap.yaml
> Add a new log graph for served artifact size

- Dockerfile
- deploy/clowdapp.yaml
- images/assets/patches/0010-Added-ability-to-return-a-URL-for-a-blob.patch
- images/assets/patches/0011-ocistorage-backend-changes.patch
- pulp_service/pulp_service/app/middleware.py
- pulp_service/pulp_service/app/storage.py
- pulp_service/requirements.txt
This reverts commit ad9b06775a0fa97d2d05b89c2319133545c5866e.
> Reapply "Adds OCIStorage backend and middleware for OCIStorage backend. (#334)" (#335)

- images/assets/patches/0011-ocistorage-backend-changes.patch
- pulp_service/pulp_service/app/middleware.py
Needed to check that the repository is a PRN and not an HREF.
> Improves OCIStorage middleware

- images/assets/patches/0011-ocistorage-backend-changes.patch
Also makes sure that 'repository' is not None before trying to resolve the PRN.
> Unset the ContextVar after getting value.

- pulp_service/pulp_service/app/models.py
- pulp_service/pulp_service/app/settings.py
- pulp_service/pulp_service/app/urls.py
- pulp_service/pulp_service/app/viewsets.py
- **Add a new route useful to debug authentication headers**
- **Add a debug feature for authentication headers in the EUS ContentGuard**
> Authentication Header debug tools

- deploy/clowdapp.yaml
> Fix the terminationGracePeriodSeconds definition

- deploy/clowdapp.yaml
> Add response time to pulp-api access log

- deploy/dashboards/grafana-dashboard-pulp.configmap.yaml
ref: https://issues.redhat.com/browse/PULP-246
> Add DB Free Storage to grafana dashboards

- Dockerfile
- images/assets/patches/0015-Add-a-filter-for-pulp_created-for-Tasks-API.patch
Test in ephemeral env:
```
$ curl -s  -uadmin:$(oc extract secret/pulp-admin-password --to=- 2>/dev/null) http://$(oc get routes pulp-api -ojsonpath='{.spec.host}')/api/pulp/admin/tasks/?pulp_created__gte=2025-01-30T12:59:00|jq
{
"count": 1,
"next": null,
"previous": null,
"results": [
{
"pulp_href": "/api/pulp/default/api/v3/tasks/0194b74f-0775-714e-b6de-10d3d0715623/",
"prn": "prn:core.task:0194b74f-0775-714e-b6de-10d3d0715623",
"pulp_created": "2025-01-30T13:03:17.367373Z",
"pulp_last_updated": "2025-01-30T13:03:17.367399Z",
"state": "completed",
"name": "pulpcore.app.tasks.telemetry.otel_metrics",
"logging_cid": "fa53358db7c44749870e0fee25f65a68",
"created_by": null,
"unblocked_at": "2025-01-30T13:03:17.388778Z",
"started_at": "2025-01-30T13:03:17.461411Z",
"finished_at": …
```
> Add a filter for `pulp_created` for Tasks API

- deploy/clowdapp.yaml
- **Use otel-collector sidecar container**
- **fix config map name for otel-collector config**
- **Change the EXPORTER endpoint to localhost.**
> Add the otel sidecar and its configs

- deploy/clowdapp.yaml
This reverts commit ac09866d3a7bfba07c721a5a0a17fb705c6f0da1.
> Revert "Add the otel sidecar and its configs (#412)"

- deploy/clowdapp.yaml
This reverts commit a03f3481e5044fc8f28ad60f8cda03628c89cc94.
> Reapply "Add the otel sidecar and its configs (#412)" (#413)

- images/assets/patches/0011-ocistorage-backend-changes.patch
The storage settings need to be able to be blank when creating a domain using django admin UI.
> Updates patch OCI storage backend

- deploy/pulp-otel-collector.yaml
- **Move the deployment file to the correct place**
- **Fixes a missing var in the new app.**
> Fixes a missing var in the new deployment

- pulp_service/pulp_service/app/constants.py
- pulp_service/pulp_service/app/tasks/package_scan.py
- pulp_service/pulp_service/app/tasks/util.py
> Fix task stuck in running state if file not found

- pulp_service/pulp_service/app/tasks/package_scan.py
ref: https://issues.redhat.com/browse/PULP-357
> Add support to gem in vuln report endpoint

- pulp_service/pulp_service/app/tasks/package_scan.py
https://google.github.io/osv.dev/post-v1-query/#pagination
> _The OSV.dev API uses pagination for queries that return a large number of vulnerabilities. When pagination is used, the next_page_token is given in the response, indicating that there are more results to return. You will need to run additional queries using the page_token to see the remaining results, repeating queries until the next_page_token is no longer included in the response._
> Handle osv.dev request report pagination

- pulp_service/pulp_service/tests/functional/conftest.py
- pulp_service/pulp_service/tests/functional/constants.py
- pulp_service/pulp_service/tests/functional/test_vulnerability_report.py
- pulp_service/requirements.txt
- unit_test.sh
ref: https://issues.redhat.com/browse/PULP-429
> Add functional tests for all existing scan functionality

- images/assets/patches/0011-ocistorage-backend-changes.patch
- pulp_service/pulp_service/app/storage.py
The storage backend now takes a username, password, and repository name.
It also now saves artifacts with their checksum as the tag in quay.
> Adds storage settings to OCI Storage Backend.

- deploy/dashboards/grafana-dashboard-pulp.configmap.yaml
Also, the proportion of the columns is corrected given more data.
> Add a new graph for cache hits.
