deploy/clowdapp.yaml

by Clowder to a tcp:// address rather than "6379".
Fixes: #28

Workaround PULP_REDIS_PORT being accidentally set

---

deploy/clowdapp.yaml

This patch adds a job that will:
- create a new role called 'domain.admin'
- create a user 'contentsources'
- assign the 'domain.admin' role to the 'contentsources' user

Adds contentsources user and domain.admin role

---

deploy/clowdapp.yaml

This is needed to ensure that the latest image is used when running migrations.

Adds imagePullPolicy for the migrate-db job

---

deploy/clowdapp.yaml

This reverts commit db4cc314a3443f445c275257600f0da1bf718fd7.
This job needed to only run in production one time. Not needed in other environments.

Revert "Adds a ClowderJob to create insights-cicd resources (#79)"

---

deploy/clowdapp.yaml

There's no need for it because it's already defined in the config file.

Remove unneeded password argument when creating rhivos domain

---

deploy/clowdapp.yaml

Temporarily removing this so the main container can run the handle-artifact-checksums command.

Remove the init container from migrate-db

---

.tekton/pulp-deploy-and-test.yaml

This is needed after the change here: https://github.com/konflux-ci/konflux-qe-definitions/pull/21/

test-metadata task is now versioned at 0.1

---

deploy/clowdapp.yaml

This also makes contentsources user an admin in ephemeral deployments.

Switch to using DomainBasedPermission class

---

pulp_service/pulp_service/app/authorization.py

Instead of throwing a 500 error, return a 401.

Handle authorization for unauthenticated users

---

deploy/clowdapp.yaml

The job create-settings-and-ingress needs a cpu limit and request as well.

deploy: Add missing cpu limit and request

---

deploy/clowdapp.yaml
pulp_service/pulp_service/app/authorization.py

The user is only able to kick off the task, but not actually monitor the task that is
happening in the Default domain.
This also makes contentsources user non-admin again.

Adds ability to PATCH and DELETE domains

---

deploy/clowdapp.yaml
pulp_service/pulp_service/app/middleware.py

The request needs to have a X-PROFILE-REQUEST header for the middleware to generate a profile. The middleware logs a URL that can be used to download the profile.

Adds middleware that generates cProfile profile for a request

---

images/assets/patches/0006-Add-the-http-target-to-pulp-api-instrumentation.patch

This addresses the remaining bugs related to processing http_target. The commit fixes paths in the following formats:
- "/api/pulp/{domain}/api/v3/repositories/rpm/rpm/{uuid}/versions/4/"
- "/api/pulp/{domain}/api/v3/users/11/"
- "/api/pulp-admin/service/domainorg/54/change/"
- "/api/pulp/assets/admin/css/widgets.css"
- "/api/pulp/pypi/decko-python-content-test/python/simple/"

Fix additional paths for http_target (last fix)

---

deploy/clowdapp.yaml
pulp_service/pulp_service/app/content.py
pulp_service/pulp_service/app/middleware.py
pulp_service/pulp_service/app/util.py

In this commit, the `pulp_http_server_custom_request_duration_milliseconds_*` metric was split into two `pulp_content_request_duration_milliseconds_*` and `pulp_api_request_duration_milliseconds_*` metrics.
Even though these metrics are self-explanatory, it is still recommended to specify "service.name". Otherwise, "exported_job" on the collector's side will be set to "unknown_service".

Add a custom metrics middleware for pulp-content

---

deploy/dashboards/grafana-dashboard-pulp.configmap.yaml

Also, queries for the existing graphs were improved. The min step was downscaled from 2m to 1m and the usual rate(interval[5m]) was replaced by increase(interval[30m]). Finally, the graphs monitoring the domains' utilization are now displaying only the top 5 domains sorted by usage.

Update the dashboard to show the latest custom metrics

---

deploy/clowdapp.yaml

Update the METRIC_EXPORT interval to get a more accurate output (for example, a burst of thousands of requests in a matter of 5~10 seconds not being visible in graphs).

Add `OTEL_METRIC_EXPORT_` env vars to content pods

---

Dockerfile
images/assets/patches/0012-content-otel-instrumentation-exception.patch

This change will handle all exceptions (including FileNotFound, for example) and will store them as a 5xx.

Catch all exceptions in metrics instrumentation

---

deploy/dashboards/grafana-dashboard-pulp.configmap.yaml

* re-organize latency and rps panels by pulpcore pod types
* modify request rate queries (kept the old ones disabled to make it easier to roll back or compare the outputs)
* decreased the dashboard default "time range" to avoid error trying to pull a lot of metrics at once and the graphs "crashing"
* modified the "graph tooltip" to "shared tooltip"
* modified request rate panels legend to table and added the max/mean/last counters

Update grafana dashboard

---

deploy/dashboards/grafana-dashboard-pulp.configmap.yaml

The new cluster var will change the datasource (prometheus metrics) and logsource (cloudwatch logs) based on its definition.

Add cluster var to grafana dashboard

---

pulp_service/pulp_service/app/admin.py

Extend the allowed chars for usernames in the admin ui, to accommodate for LDAP format of usernames 
Update the helper texts to display the new allowed chars

extend the allowed chars and helper texts

---

Dockerfile
images/assets/patches/0020-Add-uvloop-as-the-the-Gunicorn-worker-eventloop.patch
pulp_service/requirements.txt

Experiement with `uvloop`: https://github.com/pulp/pulpcore/issues/6021
Setting `PULP_USE_UVLOOP` to anything will enable it, while not having is set uses the regular worker.

[PULP-213] Add PULP_USE_UVLOOP envvar to activate uvloop in the content-app

---

images/assets/patches/0018-Re-root-the-registry-API-at-api-pulp-v2.patch

This is a temporary workaround until we get full domain support in pulp_container.

Allows non-admin users to push images to the container registry.

---

pulp_service/pulp_service/app/viewsets.py

ref: https://issues.redhat.com/browse/PULP-414

Add delete to vulnreport endpoint

---

Dockerfile
images/assets/patches/0021-Fix-handler-code-when-content-length-is-not-known.patch

This commit fixes an issue in telemetry when the  content-length is unknown and an the artifact size is `None`

Fix handler code when content length is not known

---

images/assets/patches/0022-Adds-authentication-to-the-mvn-deploy-api.patch

This is needed so we don't have to reconfigure turnpike.

Re-roots the mvn deploy api

---

deploy/clowdapp.yaml
deploy/dashboards/grafana-dashboard-pulp.configmap.yaml

- **Set some keywords to easily parse logs when it's needed.**
- **Change the query to use the new parseable artifact_size info.**

Add some keywords to log entries to parse it easily

---

deploy/clowdapp.yaml

Having an environment name ("stage", in this case) as part of the default doesn't seem a good practice, so remove it making it "environment"-agnostic.

Change default `OBJECT_STORE_NAME` to not mention environment
